---
title: "Arizona_map"
author: "Maxwel Coura Oliveira"
date: "5/1/2021"
output: html_document
---


```{r}
library(tidyverse)
library(sf)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(lwgeom)
```


```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

```{r}
(sites <- data.frame(longitude = c(-80.144005, -80.109), 
                     latitude = c(26.479005, 26.83)))
```

```{r}
library(maps)
library(tools)
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
states <- cbind(states, st_coordinates(st_centroid(states)))
states$ID <- toTitleCase(states$ID)
head(states)
```


```{r}
counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))
counties <- subset(counties, grepl("arizona", counties$ID))
counties$area <- as.numeric(st_area(counties))
head(counties)
```


```{r}
ggplot(data = world) +
  geom_sf() +
  geom_sf(data = states, fill = "white") + 
  geom_sf(data = counties, fill = "grey90", color = gray(.5)) +
  geom_sf(data = cotton_state, aes(fill = Value)) +
#  geom_sf(data = counties, aes(fill = area)) +
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
#  geom_label(data = states, aes(X, Y, label = ID), size = 5) +
#    geom_label(data = counties, aes(X, Y, label = ID)) +
    coord_sf(xlim = c(-116, -107), ylim = c(30, 38), expand = FALSE) +
  theme(panel.grid.major = element_line(colour = gray(0.5), linetype = "dashed", 
         size = 0.5), panel.background = element_rect(fill = "aliceblue"), 
         panel.border = element_rect(fill = NA)) +
  ggsave("arizona_cotton.pdf")
```

